name: Yet Another PMD Scan GitHub Action

on:
  pull_request:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**
  push:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.35.2
      - uses: actions/checkout@v3
      - id: changed-files
        uses: tj-actions/changed-files@7fc073d92265804a8d4e4982b637dee053daf6c5 # v42.0.7
      - name: Store changed files in env
        run: echo "GITHUB_MODIFIED_FILES=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_ENV
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v1.35.2

  test_checksum:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.
        with:
          create-github-annotations: "false"
          classpath-enable: "false"
