name: Yet Another PMD Scan GitHub Action

on:
  pull_request:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**
  push:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v8.2.0
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changed-files
        uses: Alfresco/alfresco-build-tools/.github/actions/github-list-changes@v8.2.0
        with:
          write-list-to-env: true
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v8.2.0

  test_scan:
    name: "Run test scan against this repository."
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.
        with:
          create-github-annotations: "false"
          classpath-enable: "false"
